// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAw8Q7_MuowtbhKzreHbywIzgKZVD0Feis',
    appId: '1:1063454844450:web:1ecbb094897f91c6228c7b',
    messagingSenderId: '1063454844450',
    projectId: 'fir-flutter-c2796',
    authDomain: 'fir-flutter-c2796.firebaseapp.com',
    storageBucket: 'fir-flutter-c2796.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuDN61mk7syiERlDtTyh56E3NlOUIgAUw',
    appId: '1:1063454844450:android:dde99ce0f32de8ed228c7b',
    messagingSenderId: '1063454844450',
    projectId: 'fir-flutter-c2796',
    storageBucket: 'fir-flutter-c2796.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4fqqaqDA3dW1gy-5btzH44KaVQFoDw-M',
    appId: '1:1063454844450:ios:3b841665dcd32ce2228c7b',
    messagingSenderId: '1063454844450',
    projectId: 'fir-flutter-c2796',
    storageBucket: 'fir-flutter-c2796.appspot.com',
    iosBundleId: 'com.example.praktikumPertemuan9',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4fqqaqDA3dW1gy-5btzH44KaVQFoDw-M',
    appId: '1:1063454844450:ios:d62dbf15fa966934228c7b',
    messagingSenderId: '1063454844450',
    projectId: 'fir-flutter-c2796',
    storageBucket: 'fir-flutter-c2796.appspot.com',
    iosBundleId: 'com.example.praktikumPertemuan9.RunnerTests',
  );
}
